project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "qmd/*.qmd"

website:
  title: "R Project - Flight Delays Analysis"
  site-url: "https://helabhl.github.io/Flight-Delays-Analysis/"
  repo-url: "https://github.com/helabhl/Flight-Delays-Analysis"
  
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Project
        contents:
          - qmd/01_data_loading_cleaning.qmd
          - qmd/02_descriptive_statistics.qmd
          - qmd/03_causes_and_seasonality.qmd
          - qmd/04_temporal_dynamics.qmd
          - qmd/05_airline_performance.qmd
      - section: Presentation
        contents:
          - qmd/presentation.qmd
      

format:
  html:
    theme: light
    css: thpe.css
    toc: true
    number-sections: true
    code-fold: true
    code-summary: "Show code"
    code-link: true
    code-overflow: scroll
  pdf:
    toc: false
    number-sections: true
    colorlinks: true
    papersize: a4
    geometry:
      - top=20mm
      - left=25mm
      - bottom=25mm

# Configuration WebR (R seulement)
webr:
  packages: ["dplyr", "ggplot2", "readxl", "tidyr", "lubridate", "car", "lmtest","curl", "googledrive"]

execute:
  freeze: true
  cache: false
  echo: false
  warning: false
  message: false
  engine: r  # ← FORCER l'utilisation de R seulement

# DÉSACTIVER Jupyter
kernel:
  jupyter: false

bibliography: bib.bib
csl: apa.csl

latex-auto-install: true